export const SUBMIT_REGISTRATION_FORM = 'SUBMIT_REGISTRATION_FORM';
export const PAN_VERIFICATION_SUCCESS = 'PAN_VERIFICATION_SUCCESS';
export const PAN_VERIFICATION_FAILURE = 'PAN_VERIFICATION_FAILURE';